# Generated by Django 3.2.11 on 2022-02-14 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import webAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceID', models.CharField(default=webAPI.models.generateInvoiceID, max_length=20)),
                ('shippingAddress', models.TextField(blank=True, null=True)),
                ('billingAddress', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('grandTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('status', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotationNo', models.CharField(default=webAPI.models.generateQuotationNo, max_length=15)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalCharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grandTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refId', models.CharField(default='N/A', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('transactionType', models.CharField(default='D', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionDateTime', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=120)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuotationItems', to='webAPI.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeName', models.CharField(max_length=20)),
                ('chargeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuotationCharges', to='webAPI.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=120)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='webAPI.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeName', models.CharField(max_length=20)),
                ('chargeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='webAPI.invoice')),
            ],
        ),
    ]
