# Generated by Django 3.2.4 on 2021-06-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0003_auto_20210621_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
    ]
