# Generated by Django 3.2.4 on 2021-07-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0004_servicelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreditledger',
            name='refId',
            field=models.CharField(default='N/A', max_length=120),
        ),
    ]
