# Generated by Django 3.2.4 on 2021-07-31 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0007_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeName', models.CharField(max_length=20)),
                ('chargeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='webAPI.invoice')),
            ],
        ),
    ]
