# Generated by Django 3.2.4 on 2021-07-31 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0008_invoicecharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecharges',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='webAPI.invoice'),
        ),
    ]
