# Generated by Django 3.2.4 on 2021-08-07 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0010_alter_usercreditledger_transactiondatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreditledger',
            name='transactionDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
