# Generated by Django 3.2.11 on 2022-01-18 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0011_alter_usercreditledger_transactiondatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreditledger',
            name='transactionDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
