# Generated by Django 3.2.11 on 2022-02-07 13:42

from django.db import migrations, models
import django.db.models.deletion
import webAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0012_alter_usercreditledger_transactiondatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotationNo', models.CharField(default=webAPI.models.generateQuotationNo, max_length=15)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalCharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grandTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=120)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuotationItems', to='webAPI.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeName', models.CharField(max_length=20)),
                ('chargeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuotationCharges', to='webAPI.quotation')),
            ],
        ),
    ]
