# Generated by Django 3.2.11 on 2022-02-14 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mobileAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaType', models.CharField(choices=[('V', 'V'), ('I', 'I')], max_length=1)),
                ('mediaUrl', models.FileField(upload_to='ProductMedia/')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rPriceQuantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gPriceQuantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hPriceQuantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avlQty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='category/')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('media', models.ManyToManyField(related_name='productMedia', to='mobileAPI.ProductMedia')),
                ('types', models.ManyToManyField(related_name='productTypes', to='mobileAPI.Type')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(default='BAGS', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileAPI.product')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileAPI.type')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=255)),
                ('phoneNo', models.CharField(max_length=15)),
                ('altPhoneNo', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserAddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(default=mobileAPI.models.generateOrderId, max_length=255)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('isInvoiceCreated', models.BooleanField(default=False)),
                ('isCashOnDelivery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billingAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BillingAddress', to='mobileAPI.orderaddress')),
                ('items', models.ManyToManyField(related_name='OrderItems', to='mobileAPI.OrderItem')),
                ('shippingAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShippingAddress', to='mobileAPI.orderaddress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserOrders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryType', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryType', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(default='BAGS', max_length=25)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartProducts', to='mobileAPI.product')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartProductTypes', to='mobileAPI.type')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cartItems', models.ManyToManyField(related_name='CartItems', to='mobileAPI.CartItem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
