# Generated by Django 3.2 on 2021-05-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileAPI', '0004_auto_20210430_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stockUnit', models.CharField(max_length=20)),
                ('priceUnit', models.CharField(max_length=20)),
                ('priceQuantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchaseUnit', models.CharField(max_length=20)),
                ('avlQty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='avlQty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pricePerQty',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(to='mobileAPI.Type'),
        ),
    ]
