# Generated by Django 3.2 on 2021-05-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileAPI', '0005_auto_20210506_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='priceQuantity',
            new_name='gPriceQuantity',
        ),
        migrations.RemoveField(
            model_name='type',
            name='priceUnit',
        ),
        migrations.AddField(
            model_name='type',
            name='gPriceUnit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='hPriceQuantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='type',
            name='hPriceUnit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='rPriceQuantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='type',
            name='rPriceUnit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
