# Generated by Django 3.2 on 2021-05-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileAPI', '0006_auto_20210506_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaType', models.CharField(choices=[('V', 'V'), ('I', 'I')], max_length=1)),
                ('mediaUrl', models.FileField(upload_to='ProductMedia/')),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='gPriceUnit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='hPriceUnit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='rPriceUnit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='media',
            field=models.ManyToManyField(to='mobileAPI.ProductMedia'),
        ),
    ]
