# Generated by Django 3.2.2 on 2021-05-11 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobileAPI', '0007_auto_20210506_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartProducts', to='mobileAPI.product')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartProductTypes', to='mobileAPI.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartItems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
