# Generated by Django 3.2.2 on 2021-05-15 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mobileAPI.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobileAPI', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ManyToManyField(related_name='productMedia', to='mobileAPI.ProductMedia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(related_name='productTypes', to='mobileAPI.Type'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileAPI.product')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileAPI.type')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=255)),
                ('phoneNo', models.CharField(max_length=15)),
                ('altPhoneNo', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserAddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(default=mobileAPI.models.generateOrderId, max_length=255)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billingAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BillingAddress', to='mobileAPI.orderaddress')),
                ('items', models.ManyToManyField(related_name='OrderItems', to='mobileAPI.OrderItem')),
                ('shippingAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShippingAddress', to='mobileAPI.orderaddress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserOrders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
