# Generated by Django 3.2.4 on 2021-08-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileAPI', '0017_order_isinvoicecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='gPriceUnit',
        ),
        migrations.RemoveField(
            model_name='type',
            name='hPriceUnit',
        ),
        migrations.RemoveField(
            model_name='type',
            name='purchaseUnit',
        ),
        migrations.RemoveField(
            model_name='type',
            name='rPriceUnit',
        ),
        migrations.RemoveField(
            model_name='type',
            name='stockUnit',
        ),
    ]
