# Generated by Django 3.2.4 on 2021-08-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileAPI', '0018_auto_20210807_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='name',
            field=models.CharField(default='Anonymous', max_length=120),
            preserve_default=False,
        ),
    ]
