# Generated by Django 3.2.11 on 2022-01-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileAPI', '0020_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isCashOnDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
